### ISSUE TITLE
Hijacker don't find any networks

### ISSUE THREAD

**Issue by deltaxflux** [chrisk44/Hijacker#27]
Well, a couple of days ago I tried hijacker but if I use it no network appear. I had to enable monitor mode manually and run airodump-ng in the background to resolve that. Here is (hopefully) all you need.

----

#### Specs
**Device:** Oneplus 5
**Kernel:** 4.4.84 / bughunter kernel
**Rom:** Oxygen OS 4.5.12 
**Rooted:** Yes
**Nethunter installed:** Yes, full chroot
**Network antenna:** Alfa awus036nh
**Support monitor mode:** Yes
**Able to capture manually:** Yes

----

#### Background

I'm also able to enable monitor mode or any other mode (e.g. master mode). Even if I enable monitor mode manually, Hijacker is able to capture only a view networks but if I run airodump-ng in the background all networks appear. It is **not** a bug with high priority because the app is still functional but is kind of annoying. If you have any problems to reproduce the issue let me know. Here are the following steps:

#### Steps

1.  Open the app and choose my wireless card
2. Start airodump-ng
3. No networks appear because Hijacker is not able to enable the monitor mode even if I use a custom command: `airmon-ng start wlan1`
4. Enable monitor mode manually 
5. Run airodump-ng manually in the background using nethunter
6. All networks appear

--------

#### Screenshots and proves 
![alt text](https://i.imgur.com/xNhkVJu.jpg)
![alt text](https://i.imgur.com/nuRkVay.jpg)

#### Edit:
I recommend to have an issue template like I have in [my project](https://github.com/FluxionNetwork/fluxion). Also take a look how an [issue template](https://github.com/FluxionNetwork/fluxion/blob/master/.github/ISSUE_TEMPLATE.md) is created. If you have any trouble or help let me know.

**Regards,** 
deltax

**Comment by chrisk44** [comment]
First of all let's leave nethunter out of this for now. Unless you are using reaver with pixie-dust, nethunter has nothing to do with the app.

From the above, I understood that:
1. You have an external wireless adapter that supports monitor mode in Android
2. You can enable monitor mode **in the android environment** manually (don't mess with nethunter)
3. You have set the interface name in Hijacker and the "Enable monitor mode" command to `airmon-ng start wlan1`.
4. Airmon-ng is installed in your device and accessible form any root shell via PATH with a simple `airmon-ng <args>` (No LD_PRELOADs or anything).
5. You run Hijacker, airodump-ng starts but no networks appear. You **know** that this is because the adapter is not in monitor mode. 

Then I'm lost. You said you run airodump-ng in nethunter, and all networks appear.
Where do they appear? Hijacker or Nethunter?
What if you empty the enable/disable monitor mode commands in Hijacker, then enable monitor mode manually and then open the app. Will this work? If so, then the problem is just that the app doesn't enable monitor mode for some reason.
Is the watchdog enabled in the app so we know that airodump is indeed running?
Do the app tests all pass?

**Comment by deltaxflux** [comment]
Well, thanks for the quick response. I think you misunderstood me. What has reaver to do with airodump-ng ? Both are separate packages and I capture networks in hijacker using airodump-ng.
1. Yes I do.
2. Yes, everything is working fine.
3. Yes I have.
4. It is installed.
5. No its not. As I said if I do all following steps manually I don't have any problem means that my network adapter is not the problem. I could double check it using aireplay-ng -9 [wireless card] but I use this card for a long time.

> Then I'm lost. You said you run airodump-ng in nethunter, and all networks appear.
Where do they appear? Hijacker or Nethunter?

Well if I do it manually networks appear in hihacker and in the manually launched airodump-ng window in nethunter.

> What if you empty the enable/disable monitor mode commands in Hijacker, then enable monitor mode manually and then open the app

As far as I can tell it is not. I modified also the disable command

> Is the watchdog enabled in the app so we know that airodump is indeed running?

Yes watchdog is enabled. Airodump-ng is running properly if I launch it manually.

> Do the app tests all pass?

Airodump-ng is found

**Regards,**
deltax

**Comment by chrisk44** [comment]
So you need to run airodump-ng in Nethunter for Hijacker to show networks? That doesn't make any sense...

**Comment by deltaxflux** [comment]
That's why I request this issue. I can capture networks but only 2 out of 20. If I run it manually in the background it captures every network.

**Comment by chrisk44** [comment]
Go to settings->copy test command and select airodump. Open a root shell and run the command. What does it show?

**Comment by deltaxflux** [comment]
Reaver terminated instantly.

**Comment by chrisk44** [comment]
If you leave the app open, then the Watchdog will detect the running process and kill it. Close the app and then run the command.

By the way, why reaver?

**Comment by deltaxflux** [comment]
Edit: that what appears if I run the test command. I figured out which command is meant.
`airodump-ng [card]` and as I said it is working.

**Comment by chrisk44** [comment]
So, if you manually run `airmon-ng start wlan1` and then `LD_PREALOAD=... (something with Hijacker directories) .../bin/airodump-ng wlan1` **in Android**, you can see all the networks?

**Comment by chrisk44** [comment]
And if you run just the airmon command manually and then open the app, only a few of the networks appear?

**Comment by deltaxflux** [comment]
Yes, this is the case.

**Comment by chrisk44** [comment]
With the enable and disable monitor mode commands empty?

**Comment by deltaxflux** [comment]
Jep I don't think that we will find any solution without bug fixing. Closing for now.
