### ISSUE TITLE
Upload to Playstore

### ISSUE THREAD

**Issue by nguyenhopquang** [chrisk44/Hijacker#46]
Can we complile and Upload this app to playstore?

**Comment by chrisk44** [comment]
You mean "Will I do that" or "Can **you** do that"?

**I** will not, because I don't think it is fit to be in PlayStore, and also my Google account is not a "developer account".
**You** can, the app is open source and you are free to do whatever you want with it. However, I would not appreciate it, as it is my work, and any help or updates will be provided through here.
