### ISSUE TITLE
handshake c.cap is empty like fake file hijacker is not hacking any wifi 

### ISSUE THREAD

**Issue by muksathegreat1** [chrisk44/Hijacker#52]
i successfully handshake with wifi but when i crack handshake.cap by aircrack-ng it show no data empty .

**Comment by chrisk44** [comment]
I closed your other issue for a reason. The template is also there for a reason. If you can't use it and you don't understand what the app does and how it's supposed to work, I can't help you. "it cannot hack any wifi" is not an acceptable bug report.

FYI, when the AP uses AES encyption (instead of TKIP), the handshake is not always (if at all) captured. 
Please don't open useless issues on the project.
