### ISSUE TITLE
Please lg g2

### ISSUE THREAD

**Issue by Ccracker22** [chrisk44/Hijacker#63]
Does anyone use hijacker on lg g 2
It is really supported ?
In the nexmon readme
Lg g2 use bcm4335 which is not supported by hijacker
But in hijacker readme lg g2 use bcm4339 and its supported ???!!

**Comment by Ccracker22** [comment]
Give to me list of supported devices

**Comment by chrisk44** [comment]
LG G2 has the same chipset as Nexus 5, MSM8974, which has the BCM4339 WiFi adapter. LG G2 is supported and if you run the app you should see the option to install the firmware.

I see the file you are talking about in the nexmon repo and I think it's wrong, because all of the other devices under BCM4335 has completely different chipsets.
