### ISSUE TITLE
Help with the setup

### ISSUE THREAD

**Issue by kaloyan132** [chrisk44/Hijacker#85]
Hi i didnt have success with kali vm and a wireless card that enters in monitor mode
(Ralink rt5372L)
So i googled phone cards that support it and my old moms phone lg g4(c90)(h525n)
Has 4339 chipset so i ask you for link to custom os download i have rooted phones before like my galaxy s6 edge and some others not for hacking purposes i will be really gratefull 
Sorry for bad english
Custom firmwate to be correct now that i checked

**Comment by chrisk44** [comment]
The app can work on any Android device, provided it meets the requirements posted in the project's README. The firmware for BCM4339 is provided by the app so if your device is compatible then you will have the option to install the custom firmware through the app, otherwise it's on you to install a custom firmware.

**Comment by kaloyan132** [comment]
So if i have even stock 5+ android rooted it will work?

**Comment by chrisk44** [comment]
As long as the firmware supports monitor mode and it's correctly rooted, yes. Read the README.
