### ISSUE TITLE
Windows Security Threat blocked

### ISSUE THREAD

**Issue by MasKhan20** [chrisk44/Hijacker#93]
## Current Behavior

Windows Antivirus blocks download detecting Backdoor:Win32/Berbew
Details: This program provides remote access to the computer it is installed on

![Threat](https://user-images.githubusercontent.com/32960553/90401148-753e7d80-e095-11ea-89cf-361ce6a39029.png)

## Expected Behavior

Download release without any issues.

I would have allowed the threat if it came up as a HackTool, but the remote access part raises my eyebrow.

## Detailed steps to reproduce the problem
1. Download latest release

## Device details

Windows 10

## Suggested Solution

Reupload original aircrack-ng binaries from their website.

Does everyone have this problem or is an external attacker modifying your release on it way to my PC?

**Comment by chrisk44** [comment]
Given the fact that this file is supposed to end up on an Android device, it seems weird that it would contain malicius code for Win32. I mean, even if I wanted to do something like that, why would I put a Windows virus in an apk file?
My guess is that you followed a link from somewhere that led you to a malicious download. Please make sure you're downloading any Hijacker apks only from the official [releases](https://github.com/chrisk44/Hijacker/releases) page on GitHub.

The latest release on GitHub that I just downloaded has the same MD5 sum with the file that I uploaded on February, so it's fine.
If still in doubt, you can always check out the code by yourself and built the apk on your own (the whole point of open source).

**Comment by chrisk44** [comment]
A difference in `aircrack-ng` binary between v1.5-beta.11 and v1.5-beta.12 doesn't make any sense, because as you can see in the repo the file hasn't been changed in 4 years.

Now, 4 years ago, those files were compiled using the [nexmon](https://github.com/seemoo-lab/nexmon) repository. Something has clearly changed in the last 4 years because the MD5s of the files I just built don't match with the ones that Hijacker contains. In any case, you can always download the source, build your own binaries, and build the app. Both Hijacker and Nexmon are well set up and documented so you shouldn't have any problems doing that.

**Comment by MasKhan1223** [comment]
On my machine, the MD5 checksum of `Hijacker-release-v1.5-beta.12.apk` is `69b5332cae824b7446c86ae1fb0cfe55`.

![image](https://user-images.githubusercontent.com/32960553/91439510-ff8c9b80-e864-11ea-9495-fca086f103ff.png)

Does that match with yours? I believe someone may be modifying the file as I attempt to download it. Am I the only one with this issue?

**Comment by chrisk44** [comment]
Yes, this is correct. There haven't been any reports like this. At this point I'm questioning your antivirus software.

**Comment by MasKhan1223** [comment]
No threats found when downloaded on a fresh installation of windows. Closing this issue since it - only doesn't work on my machine.
