### ISSUE TITLE
Unable to show surrounding wifi

### ISSUE THREAD

**Issue by D-Jiang** [chrisk44/Hijacker#97]
The following prompt appears when you run the software. I'm using Android 10, I think it's possible that the permission management mechanism of Android 10 is different from previous versions, you need to apply for location access to scan for nearby wifi. hope to adapt! Thanks!
![IMG_20210111_084009](https://user-images.githubusercontent.com/62754983/104139819-ea19a780-53e8-11eb-808c-9ec82644e1e4.jpg)

**Comment by chrisk44** [comment]
Countless things could have gone wrong for this to appear, but Android's permissions management mechanism is definately not one of them. For some reason, airodump-ng has failed to start. This was most likely because of an unsupported device, lack of root access/permission, unsupported CPU architecture, wifi not in monitor mode, wifi not enabled, and so on...
Please consult the project's README for details about this error.

Also, in the project's README you will find a discontinuation announcement along with some information about the upcoming version. Even if your issue is not 'unsupported device' or 'not in monitor mode' which would be the user's responsibility (you), the new version will not use airodump-ng (so any changes would be irrelevant), and the old code base is just too weird for me to work on it and figure out what went wrong in your case.

Please follow the instructions in the repo's readme, and stay tuned for the next iteration of the project.
